# Generated by Django 6.0.4 on 2026-04-16 13:50

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerie', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galeriepage',
            name='albums',
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('date', models.DateField(blank=True, help_text="Date de l'événement (pour le tri)", null=True)),
                ('couverture', models.ForeignKey(blank=True, help_text="Image de couverture de l'album (optionnel, sinon la 1ère photo sera utilisée)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Album photo',
                'verbose_name_plural': 'Albums photos',
                'ordering': ['-date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='AlbumPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('legende', models.CharField(blank=True, help_text='Optionnel — courte description de la photo', max_length=200, verbose_name='Légende')),
                ('album', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='galerie.album')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Photo',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
