# Generated by Django 6.0.4 on 2026-04-16 12:50

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': "Page d'accueil"},
        ),
        migrations.AddField(
            model_name='homepage',
            name='annee_creation',
            field=models.PositiveIntegerField(default=1970, verbose_name='Année de création'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='ecole_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='ecole_texte',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='ecole_titre',
            field=models.CharField(blank=True, default='École de Tennis', max_length=120),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta2_texte',
            field=models.CharField(blank=True, default='Prendre ma licence', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta2_url',
            field=models.URLField(blank=True, default='https://tenup.fft.fr'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_texte',
            field=models.CharField(default='Réserver un court', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_url',
            field=models.URLField(default='https://tenup.fft.fr'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_sous_titre',
            field=models.CharField(blank=True, default="L'esprit sportif, le respect, dans un cadre accueillant, familial et festif", max_length=250),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_titre',
            field=models.CharField(default='Tennis Sporting Club Mazanais', max_length=120),
        ),
        migrations.AddField(
            model_name='homepage',
            name='nb_adherents',
            field=models.PositiveIntegerField(default=0, verbose_name="Nombre d'adhérents"),
        ),
        migrations.AddField(
            model_name='homepage',
            name='nb_courts',
            field=models.PositiveIntegerField(default=4, verbose_name='Nombre de courts'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='presentation_texte',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='presentation_titre',
            field=models.CharField(blank=True, default='Bienvenue au club', max_length=120),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sponsors',
            field=wagtail.fields.StreamField([('sponsor', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.blocks.URLBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('nom', 0), ('logo', 1), ('url', 2)]], {})}),
        ),
    ]
