# Generated by Django 6.0.4 on 2026-04-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_homepage_options_homepage_annee_creation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenup_url', models.URLField(default='https://tenup.fft.fr/club/62840344', help_text='URL de la page du club sur Tenup', verbose_name='Lien Tenup (réservation & licence)')),
                ('telephone', models.CharField(default='04 90 69 86 45', max_length=20)),
                ('email', models.EmailField(default='tscm@bbox.fr', max_length=254)),
                ('adresse', models.TextField(default='Chemin du Bigourd\nSite du COSEC\n84380 Mazan')),
                ('facebook_url', models.URLField(blank=True, default='https://www.facebook.com/profile.php?id=100010233949238')),
                ('instagram_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Paramètres du site',
            },
        ),
    ]
