# Generated by Django 6.0.4 on 2026-04-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_hero_image_mobile_alter_homepage_hero_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, verbose_name='Texte affiché')),
                ('url', models.CharField(help_text='Ex: /le-club/ ou https://tenup.fft.fr', max_length=200)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('open_new_tab', models.BooleanField(default=False, verbose_name='Ouvrir dans un nouvel onglet')),
            ],
            options={
                'verbose_name': 'Élément de menu',
                'verbose_name_plural': 'Éléments de menu',
                'ordering': ['sort_order'],
            },
        ),
    ]
