# Generated by Django 6.0.4 on 2026-04-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='nb_equipes',
            field=models.PositiveIntegerField(default=15, verbose_name="Nombre d'équipes engagées"),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='nb_adherents',
            field=models.PositiveIntegerField(default=150, verbose_name="Nombre d'adhérents"),
        ),
    ]
