# Generated by Django 6.0.4 on 2026-04-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepage_nb_equipes_alter_homepage_nb_adherents'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='shop_url',
            field=models.URLField(blank=True, default='https://www.sas-aston.fr', help_text='URL de la boutique en ligne du club. Laisser vide pour masquer le lien du site.', verbose_name='Lien boutique partenaire (ASTON)'),
        ),
    ]
