# Generated by Django 6.0.4 on 2026-04-16 12:50

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtaildocs', '0014_alter_document_file_size'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultatsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('contenu', wagtail.fields.StreamField([('section', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 120}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('titre', 0), ('contenu', 1)]], {'icon': 'doc-full', 'label': 'Section résultats'})})),
            ],
            options={
                'verbose_name': 'Page Résultats',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ClubPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('president_titre', models.CharField(default='Le mot du Président', max_length=120)),
                ('president_texte', wagtail.fields.RichTextField(blank=True)),
                ('president_nom', models.CharField(blank=True, max_length=100)),
                ('dirigeants', wagtail.fields.StreamField([('dirigeant', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 2: ('wagtail.blocks.StructBlock', [[('nom', 0), ('role', 0), ('photo', 1)]], {})})),
                ('adresse', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('president_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Page du Club',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='EcoleTennisPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('contenu', wagtail.fields.RichTextField(blank=True)),
                ('horaires', wagtail.fields.RichTextField(blank=True, verbose_name='Horaires et planning')),
                ('lien_inscription', models.URLField(blank=True, default='https://tenup.fft.fr')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Page École de Tennis',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TarifsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('contenu', wagtail.fields.RichTextField(blank=True)),
                ('lien_inscription', models.URLField(blank=True, default='https://tenup.fft.fr')),
                ('document_tarifs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document')),
            ],
            options={
                'verbose_name': 'Page Tarifs',
            },
            bases=('wagtailcore.page',),
        ),
    ]
