# Generated by Django 6.0.4 on 2026-04-16 13:35

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultatspage',
            name='contenu',
        ),
        migrations.AddField(
            model_name='resultatspage',
            name='competitions',
            field=wagtail.fields.StreamField([('competition', 12)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Ex: Open de Mazan 2025', 'max_length': 150}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 30, 'required': False}), 2: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Ex: 15 juin 2025', 'max_length': 30}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Ex: Open de Mazan, Championnat Vaucluse', 'max_length': 120}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Ex: Finale, Demi-finale, Poule', 'max_length': 80, 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': "Nom du joueur ou de l'équipe TSC", 'max_length': 150}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 150, 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Ex: 6-3 6-4, ou 5-2', 'max_length': 50, 'required': False}), 9: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'Cocher si victoire', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('date', 3), ('competition', 4), ('tour', 5), ('joueur_equipe', 6), ('adversaire', 7), ('score', 8), ('victoire', 9)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {'required': False}), 12: ('wagtail.blocks.StructBlock', [[('titre', 0), ('date_debut', 1), ('date_fin', 1), ('description', 2), ('matchs', 11)]], {})}, verbose_name='Compétitions & matchs'),
        ),
        migrations.AddField(
            model_name='resultatspage',
            name='equipes_texte',
            field=wagtail.fields.RichTextField(blank=True, help_text='Résumé libre des résultats par équipe', verbose_name='Résultats par équipes'),
        ),
        migrations.AddField(
            model_name='resultatspage',
            name='lien_fft',
            field=models.URLField(blank=True, default='https://tenup.fft.fr/club/62840344', verbose_name='Lien FFT / Tenup résultats'),
        ),
        migrations.AddField(
            model_name='resultatspage',
            name='palmares',
            field=wagtail.fields.StreamField([('palmares', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Ex: 2025, 2024/2025', 'max_length': 10}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Ex: Champions de Vaucluse Jeunes 17/18', 'max_length': 150}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Ex: Jeunes, Séniors, Dames', 'max_length': 50, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Ex: Départemental, Régional', 'max_length': 50, 'required': False}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 5: ('wagtail.blocks.StructBlock', [[('annee', 0), ('titre', 1), ('categorie', 2), ('niveau', 3), ('photo', 4)]], {})}, verbose_name='Palmarès du club'),
        ),
    ]
