# Generated by Django 6.0.4 on 2026-04-16 13:50

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_remove_resultatspage_contenu_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Ex: Open de Mazan 2025', max_length=150)),
                ('saison', models.CharField(blank=True, help_text='Ex: 2024/2025', max_length=20)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('description', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Compétition',
                'ordering': ['-date_debut', '-pk'],
            },
        ),
        migrations.RemoveField(
            model_name='resultatspage',
            name='competitions',
        ),
        migrations.RemoveField(
            model_name='resultatspage',
            name='palmares',
        ),
        migrations.AlterField(
            model_name='resultatspage',
            name='lien_fft',
            field=models.URLField(blank=True, default='https://tenup.fft.fr/club/62840344', verbose_name='Lien FFT / Tenup'),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('tour', models.CharField(blank=True, help_text='Ex: Finale, 1/2 finale', max_length=80)),
                ('joueur_equipe', models.CharField(max_length=150, verbose_name='Joueur / Équipe TSC')),
                ('adversaire', models.CharField(blank=True, max_length=150)),
                ('score', models.CharField(blank=True, help_text='Ex: 6-3 6-4', max_length=50)),
                ('victoire', models.BooleanField(default=False, verbose_name='Victoire ?')),
                ('competition', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchs', to='club.competition')),
            ],
            options={
                'verbose_name': 'Match',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Palmares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.CharField(help_text='Ex: 2025', max_length=10, verbose_name='Année')),
                ('titre', models.CharField(help_text='Ex: Champions de Vaucluse Jeunes 17/18', max_length=150)),
                ('categorie', models.CharField(blank=True, choices=[('jeunes', 'Jeunes'), ('seniors', 'Séniors'), ('dames', 'Dames'), ('mixte', 'Mixte')], max_length=20)),
                ('niveau', models.CharField(blank=True, choices=[('departemental', 'Départemental'), ('regional', 'Régional'), ('national', 'National')], max_length=20)),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Palmarès',
                'verbose_name_plural': 'Palmarès',
                'ordering': ['-annee', 'titre'],
            },
        ),
    ]
