# Generated by Django 6.0.4 on 2026-04-19 17:33

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_competition_remove_resultatspage_competitions_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartenairesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Accroche en haut de page (sous le titre hero).')),
                ('offre_personnalisee_texte', wagtail.fields.RichTextField(blank=True, help_text='Bloc "Offre sur mesure" après les 4 offres standards.', verbose_name="Texte de l'offre personnalisée")),
            ],
            options={
                'verbose_name': 'Page Partenaires',
            },
            bases=('wagtailcore.page',),
        ),
    ]
