# Generated by Django 6.0.4 on 2026-04-20 09:25

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_partenairespage'),
    ]

    operations = [
        migrations.AddField(
            model_name='partenairespage',
            name='hero_eyebrow',
            field=models.CharField(default='Sponsoring & Partenariat', max_length=120, verbose_name='Sur-titre du hero'),
        ),
        migrations.AddField(
            model_name='partenairespage',
            name='hero_titre',
            field=models.CharField(default='Devenez partenaire du TSCM', max_length=200, verbose_name='Titre du hero'),
        ),
        migrations.AddField(
            model_name='partenairespage',
            name='offre_1_badge',
            field=models.CharField(default='Exclusivité', max_length=40, verbose_name='Offre 1 — badge'),
        ),
        migrations.AddField(
            model_name='partenairespage',
            name='offre_1_bullet_1',
            field=models.CharField(default='Environ 30 t-shirts par production', max_length=160, verbose_name='Offre 1 — point 1'),
        ),
        migrations.AddField(
            model_name='partenairespage',
            name='offre_1_bullet_2',
            field=models.CharField(default='Visibilité sur toutes les équipes', max_length=160, verbose_name='Offre 1 — point 2'),
        ),
        migrations.AddField(
            model_name='partenairespage',
            name='offre_1_bullet_3',
            field=models.CharField(default='Diffusion pendant 1 an', max_length=160, verbose_name='Offre 1 — point 3'),
        ),
        migrations.AddField(
            model_name='partenairespage',
            name='offre_1_description',
            field=wagtail.fields.RichTextField(blank=True, default="Votre logo sur la manche des t-shirts du club, en vente toute l'année auprès de nos licenciés via notre partenaire <strong>ASTON</strong>.", verbose_name='Offre 1 — description'),
        ),
        migrations.AddField(
            model_name='partenairespage',
            name='offre_1_prix',
            field=models.CharField(default='150 €', max_length=40, verbose_name='Offre 1 — prix'),
        ),
        migrations.AddField(
            model_name='partenairespage',
            name='offre_1_prix_suffixe',
            field=models.CharField(default='/ an', max_length=40, verbose_name='Offre 1 — suffixe prix'),
        ),
        migrations.AddField(
            model_name='partenairespage',
            name='offre_1_titre',
            field=models.CharField(default='Logo en action sur nos t-shirts', max_length=200, verbose_name='Offre 1 — titre'),
        ),
        migrations.AddField(
            model_name='partenairespage',
            name='offre_2_badge',
            field=models.CharField(default='Exclusivité', max_length=40, verbose_name='Offre 2 — badge'),
        ),
        migrations.AddField(
            model_name='partenairespage',
            name='offre_2_bullet_1',
            field=models.CharField(default='4 tableaux, 4 courts', max_length=160, verbose_name='Offre 2 — point 1'),
        ),
        migrations.AddField(
            model_name='partenairespage',
            name='offre_2_bullet_2',
            field=models.CharField(default='~100 matchs par saison', max_length=160, verbose_name='Offre 2 — point 2'),
        ),
        migrations.AddField(
            model_name='partenairespage',
            name='offre_2_bullet_3',
            field=models.CharField(default='Diffusion pendant 1 an', max_length=160, verbose_name='Offre 2 — point 3'),
        ),
        migrations.AddField(
            model_name='partenairespage',
            name='offre_2_description',
            field=wagtail.fields.RichTextField(blank=True, default='Votre logo sur les <strong>4 tableaux de scores</strong> du club — présent sur chaque match officiel, sous les yeux de joueurs et de spectateurs.', verbose_name='Offre 2 — description'),
        ),
        migrations.AddField(
            model_name='partenairespage',
            name='offre_2_prix',
            field=models.CharField(default='180 €', max_length=40, verbose_name='Offre 2 — prix'),
        ),
        migrations.AddField(
            model_name='partenairespage',
            name='offre_2_prix_suffixe',
            field=models.CharField(default='/ an', max_length=40, verbose_name='Offre 2 — suffixe prix'),
        ),
        migrations.AddField(
            model_name='partenairespage',
            name='offre_2_titre',
            field=models.CharField(default='Logo sur nos tableaux des scores', max_length=200, verbose_name='Offre 2 — titre'),
        ),
        migrations.AddField(
            model_name='partenairespage',
            name='offre_3_badge',
            field=models.CharField(default='Exclusivité', max_length=40, verbose_name='Offre 3 — badge'),
        ),
        migrations.AddField(
            model_name='partenairespage',
            name='offre_3_bullet_1',
            field=models.CharField(default='<strong>Premium</strong> — 2 filets : 200 €', max_length=160, verbose_name='Offre 3 — point 1'),
        ),
        migrations.AddField(
            model_name='partenairespage',
            name='offre_3_bullet_2',
            field=models.CharField(default='<strong>Privilège</strong> — 4 filets : 250 €', max_length=160, verbose_name='Offre 3 — point 2'),
        ),
        migrations.AddField(
            model_name='partenairespage',
            name='offre_3_bullet_3',
            field=models.CharField(default='Diffusion pendant 1 an', max_length=160, verbose_name='Offre 3 — point 3'),
        ),
        migrations.AddField(
            model_name='partenairespage',
            name='offre_3_description',
            field=wagtail.fields.RichTextField(blank=True, default="Votre logo sur <strong>2 ou 4 filets</strong> (90 × 60 cm). Seule entreprise visible sur l'un des côtés des filets pendant 1 an.", verbose_name='Offre 3 — description'),
        ),
        migrations.AddField(
            model_name='partenairespage',
            name='offre_3_prix',
            field=models.CharField(default='dès 200 €', max_length=40, verbose_name='Offre 3 — prix'),
        ),
        migrations.AddField(
            model_name='partenairespage',
            name='offre_3_prix_suffixe',
            field=models.CharField(default='/ an', max_length=40, verbose_name='Offre 3 — suffixe prix'),
        ),
        migrations.AddField(
            model_name='partenairespage',
            name='offre_3_titre',
            field=models.CharField(default='Logo sur nos filets de court', max_length=200, verbose_name='Offre 3 — titre'),
        ),
        migrations.AddField(
            model_name='partenairespage',
            name='offre_4_badge',
            field=models.CharField(default='Premium', max_length=40, verbose_name='Offre 4 — badge'),
        ),
        migrations.AddField(
            model_name='partenairespage',
            name='offre_4_bullet_1',
            field=models.CharField(default='Visibilité maximale sur court', max_length=160, verbose_name='Offre 4 — point 1'),
        ),
        migrations.AddField(
            model_name='partenairespage',
            name='offre_4_bullet_2',
            field=models.CharField(default='Fabrication possible de notre côté', max_length=160, verbose_name='Offre 4 — point 2'),
        ),
        migrations.AddField(
            model_name='partenairespage',
            name='offre_4_bullet_3',
            field=models.CharField(default='Diffusion pendant 1 an', max_length=160, verbose_name='Offre 4 — point 3'),
        ),
        migrations.AddField(
            model_name='partenairespage',
            name='offre_4_description',
            field=wagtail.fields.RichTextField(blank=True, default='Bâches <strong>2 × 1,5 m</strong> installées sur les grillages de milieu de terrain et fonds de court. Fourniture par nos soins, ou fournie par vos soins et installée par nous.', verbose_name='Offre 4 — description'),
        ),
        migrations.AddField(
            model_name='partenairespage',
            name='offre_4_prix',
            field=models.CharField(default='Sur devis', max_length=40, verbose_name='Offre 4 — prix'),
        ),
        migrations.AddField(
            model_name='partenairespage',
            name='offre_4_prix_suffixe',
            field=models.CharField(default='1 an', max_length=40, verbose_name='Offre 4 — suffixe prix'),
        ),
        migrations.AddField(
            model_name='partenairespage',
            name='offre_4_titre',
            field=models.CharField(default='Bâches publicitaires sur terrain', max_length=200, verbose_name='Offre 4 — titre'),
        ),
        migrations.AddField(
            model_name='partenairespage',
            name='offres_eyebrow',
            field=models.CharField(default='Nos offres', max_length=120, verbose_name='Sur-titre section offres'),
        ),
        migrations.AddField(
            model_name='partenairespage',
            name='offres_intro',
            field=wagtail.fields.RichTextField(blank=True, default='Du soutien à partir de <strong>150 €</strong> aux offres premium, choisissez la visibilité qui vous ressemble. Toutes nos offres sont en exclusivité ou en nombre limité.', verbose_name='Intro section offres'),
        ),
        migrations.AddField(
            model_name='partenairespage',
            name='offres_titre',
            field=models.CharField(default='4 formules pour tous les budgets', max_length=200, verbose_name='Titre section offres'),
        ),
        migrations.AddField(
            model_name='partenairespage',
            name='sur_mesure_cta_label',
            field=models.CharField(default='Construire une offre ensemble', max_length=120, verbose_name='Label du bouton sur-mesure'),
        ),
        migrations.AddField(
            model_name='partenairespage',
            name='sur_mesure_eyebrow',
            field=models.CharField(default='Sur mesure', max_length=120, verbose_name='Sur-titre section sur-mesure'),
        ),
        migrations.AddField(
            model_name='partenairespage',
            name='sur_mesure_titre',
            field=models.CharField(default='Chez nous, tout est possible', max_length=200, verbose_name='Titre section sur-mesure'),
        ),
    ]
