# Generated by Django 6.0.4 on 2026-04-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_partenairespage_hero_eyebrow_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Équipe Séniors Masculine', max_length=120)),
                ('description', models.TextField(help_text='Joueurs, capitaine, résultats marquants…')),
                ('ordre', models.PositiveIntegerField(default=0, help_text='Position dans la liste (plus petit = plus haut)')),
            ],
            options={
                'verbose_name': 'Équipe',
                'verbose_name_plural': 'Équipes',
                'ordering': ['ordre', 'nom'],
            },
        ),
    ]
