# Generated by Django 6.0.4 on 2026-04-20 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0007_import_equipes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultatspage',
            name='equipes_texte',
        ),
    ]
