# Generated by Django 6.0.4 on 2026-05-15 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0008_remove_resultatspage_equipes_texte'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dirigeant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('role', models.CharField(help_text='Ex: Président, Trésorier…', max_length=100)),
                ('ordre', models.PositiveIntegerField(default=0, help_text='Position dans la liste (plus petit = plus haut)')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Dirigeant',
                'verbose_name_plural': 'Équipe dirigeante',
                'ordering': ['ordre', 'nom'],
            },
        ),
    ]
