# Generated by Django 6.0.4 on 2026-05-15 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0010_import_dirigeants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubpage',
            name='dirigeants',
        ),
    ]
